[package]
name = "scarlet-frame"
version = "0.0.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5" }
egui = { version = "0.30.0", default-features = false, features = [ "default_fonts" ] }
